In [3]:
import pandas as pd
url= 'https://raw.githubusercontent.com/paiml/wine-ratings/main/wine-ratings.csv'
df= pd.read_csv(url,index_col=0)
df

,name,grape,region,variety,rating,notes
0,1000 Stories Bourbon Barrel Aged Batch Blue Ca...,NaN,"Mendocino, California",Red Wine,91.0,"This is a very special, limited release of 100..."
1,1000 Stories Bourbon Barrel Aged Gold Rush Red...,NaN,California,Red Wine,89.0,The California Gold Rush was a period of coura...
2,1000 Stories Bourbon Barrel Aged Gold Rush Red...,NaN,California,Red Wine,90.0,The California Gold Rush was a period of coura...
3,1000 Stories Bourbon Barrel Aged Zinfandel 2013,NaN,"North Coast, California",Red Wine,91.0,"The wine has a deep, rich purple color. An int..."
4,1000 Stories Bourbon Barrel Aged Zinfandel 2014,NaN,California,Red Wine,90.0,Batch #004 is the first release of the 2014 vi...
...,...,...,...,...,...,...
32775,Lewis Cellars Syrah Ethan's Blend 2005,NaN,California,Red Wine,92.0,"Now 7 years old, Alec's younger brother Ethan ..."
32776,Lewis Cellars Syrah Ethan's Blend 2014,NaN,California,Red Wine,93.0,"Born in 2000, everything about Ethan and his n..."
32777,Lewis Cellars Syrah Ethan's Blend 2009,NaN,California,Red Wine,94.0,"Positioned between brothers, Alec and Mason, E..."
32778,Lexington Apex Red 2011,NaN,"Santa Cruz Mountains, California",Red Wine,91.0,"Blend: 99% Cabernet Sauvignon, 1% Merlot"
32779,Lexington Gist Ranch Cabernet Sauvignon 2011,NaN,"Santa Cruz Mountains, California",Red Wine,91.0,"Blend: 80% Cabernet Sauvignon, 20% Merlot"

In [4]:
df.head(10)

,name,grape,region,variety,rating,notes
0,1000 Stories Bourbon Barrel Aged Batch Blue Ca...,NaN,"Mendocino, California",Red Wine,91.0,"This is a very special, limited release of 100..."
1,1000 Stories Bourbon Barrel Aged Gold Rush Red...,NaN,California,Red Wine,89.0,The California Gold Rush was a period of coura...
2,1000 Stories Bourbon Barrel Aged Gold Rush Red...,NaN,California,Red Wine,90.0,The California Gold Rush was a period of coura...
3,1000 Stories Bourbon Barrel Aged Zinfandel 2013,NaN,"North Coast, California",Red Wine,91.0,"The wine has a deep, rich purple color. An int..."
4,1000 Stories Bourbon Barrel Aged Zinfandel 2014,NaN,California,Red Wine,90.0,Batch #004 is the first release of the 2014 vi...
5,1000 Stories Bourbon Barrel Aged Zinfandel 2016,NaN,California,Red Wine,91.0,"1,000 Stories Bourbon barrel-aged Zinfandel is..."
6,1000 Stories Bourbon Barrel Aged Zinfandel 2017,NaN,California,Red Wine,92.0,"Batch 55 embodies an opulent vintage, which sa..."
7,12 Linajes Crianza 2014,NaN,"Ribera del Duero, Spain",Red Wine,92.0,Red with violet hues. The aromas are very inte...
8,12 Linajes Reserva 2012,NaN,"Ribera del Duero, Spain",Red Wine,94.0,"On the nose, a complex predominance of mineral..."
9,14 Hands Cabernet Sauvignon 2010,NaN,"Columbia Valley, Washington",Red Wine,87.0,Concentrated aromas of dark stone fruits and t...

### Load From File

In [8]:
import pandas as pd
df = pd.read_csv('../../data/breast-cancer.csv')
df.head()

,'40-49','premeno','15-19','0-2','yes','3','right','left_up','no','recurrence-events'
0,'50-59','ge40','15-19','0-2','no','1','right','central','no','no-recurrence-events'
1,'50-59','ge40','35-39','0-2','no','2','left','left_low','no','recurrence-events'
2,'40-49','premeno','35-39','0-2','yes','3','right','left_low','yes','no-recurrence-events'
3,'40-49','premeno','30-34','3-5','yes','2','left','right_up','no','recurrence-events'
4,'50-59','premeno','25-29','3-5','no','2','right','left_up','yes','no-recurrence-events'