In [1]:
import pandas as pd 
df = pd.read_csv('../../../data/wine-ratings.csv',index_col=0)
df.head(10)

,name,grape,region,variety,rating,notes
0,1000 Stories Bourbon Barrel Aged Batch Blue Ca...,NaN,"Mendocino, California",Red Wine,91.0,"This is a very special, limited release of 100..."
1,1000 Stories Bourbon Barrel Aged Gold Rush Red...,NaN,California,Red Wine,89.0,The California Gold Rush was a period of coura...
2,1000 Stories Bourbon Barrel Aged Gold Rush Red...,NaN,California,Red Wine,90.0,The California Gold Rush was a period of coura...
3,1000 Stories Bourbon Barrel Aged Zinfandel 2013,NaN,"North Coast, California",Red Wine,91.0,"The wine has a deep, rich purple color. An int..."
4,1000 Stories Bourbon Barrel Aged Zinfandel 2014,NaN,California,Red Wine,90.0,Batch #004 is the first release of the 2014 vi...
5,1000 Stories Bourbon Barrel Aged Zinfandel 2016,NaN,California,Red Wine,91.0,"1,000 Stories Bourbon barrel-aged Zinfandel is..."
6,1000 Stories Bourbon Barrel Aged Zinfandel 2017,NaN,California,Red Wine,92.0,"Batch 55 embodies an opulent vintage, which sa..."
7,12 Linajes Crianza 2014,NaN,"Ribera del Duero, Spain",Red Wine,92.0,Red with violet hues. The aromas are very inte...
8,12 Linajes Reserva 2012,NaN,"Ribera del Duero, Spain",Red Wine,94.0,"On the nose, a complex predominance of mineral..."
9,14 Hands Cabernet Sauvignon 2010,NaN,"Columbia Valley, Washington",Red Wine,87.0,Concentrated aromas of dark stone fruits and t...

In [4]:
def good_wine(col):
    if col > 94 :return 1
    return 0

df["good"]= df.rating.apply(good_wine) 
df.query("rating>94").head()

,name,grape,region,variety,rating,notes,good
36,3 Rings Reserve Shiraz 2004,NaN,"Barossa Valley, Barossa, South Australia, Aust...",Red Wine,96.0,Vintage Comments : Classic Barossa vintage con...,1
110,Aalto 2005,NaN,"Ribera del Duero, Spain",Red Wine,95.0,The grapes come exclusively from old vineyards...,1
111,Aalto 2007,NaN,"Ribera del Duero, Spain",Red Wine,95.0,It is ironic that one of the youngest properti...,1
113,Aalto 2008,NaN,"Ribera del Duero, Spain",Red Wine,95.0,This wine's elegance and fruitful presence per...,1
121,Aalto 2016,NaN,"Ribera del Duero, Spain",Red Wine,95.0,"Deep purple red color, as corresponds to old T...",1