In [2]:
import pandas as pd 
df = pd.read_csv('../../../data/wine-ratings.csv',index_col=0)
df.head(10)

,name,grape,region,variety,rating,notes
0,1000 Stories Bourbon Barrel Aged Batch Blue Ca...,NaN,"Mendocino, California",Red Wine,91.0,"This is a very special, limited release of 100..."
1,1000 Stories Bourbon Barrel Aged Gold Rush Red...,NaN,California,Red Wine,89.0,The California Gold Rush was a period of coura...
2,1000 Stories Bourbon Barrel Aged Gold Rush Red...,NaN,California,Red Wine,90.0,The California Gold Rush was a period of coura...
3,1000 Stories Bourbon Barrel Aged Zinfandel 2013,NaN,"North Coast, California",Red Wine,91.0,"The wine has a deep, rich purple color. An int..."
4,1000 Stories Bourbon Barrel Aged Zinfandel 2014,NaN,California,Red Wine,90.0,Batch #004 is the first release of the 2014 vi...
5,1000 Stories Bourbon Barrel Aged Zinfandel 2016,NaN,California,Red Wine,91.0,"1,000 Stories Bourbon barrel-aged Zinfandel is..."
6,1000 Stories Bourbon Barrel Aged Zinfandel 2017,NaN,California,Red Wine,92.0,"Batch 55 embodies an opulent vintage, which sa..."
7,12 Linajes Crianza 2014,NaN,"Ribera del Duero, Spain",Red Wine,92.0,Red with violet hues. The aromas are very inte...
8,12 Linajes Reserva 2012,NaN,"Ribera del Duero, Spain",Red Wine,94.0,"On the nose, a complex predominance of mineral..."
9,14 Hands Cabernet Sauvignon 2010,NaN,"Columbia Valley, Washington",Red Wine,87.0,Concentrated aromas of dark stone fruits and t...

In [4]:
df["variety_short"]= df.variety.replace({"Red Wine":"R","White Wine":"W"})
df.head()

,name,grape,region,variety,rating,notes,variety_short
0,1000 Stories Bourbon Barrel Aged Batch Blue Ca...,NaN,"Mendocino, California",Red Wine,91.0,"This is a very special, limited release of 100...",R
1,1000 Stories Bourbon Barrel Aged Gold Rush Red...,NaN,California,Red Wine,89.0,The California Gold Rush was a period of coura...,R
2,1000 Stories Bourbon Barrel Aged Gold Rush Red...,NaN,California,Red Wine,90.0,The California Gold Rush was a period of coura...,R
3,1000 Stories Bourbon Barrel Aged Zinfandel 2013,NaN,"North Coast, California",Red Wine,91.0,"The wine has a deep, rich purple color. An int...",R
4,1000 Stories Bourbon Barrel Aged Zinfandel 2014,NaN,California,Red Wine,90.0,Batch #004 is the first release of the 2014 vi...,R

In [6]:
df["regoin_short"]= df.region.str.split().str.get(-1)

df.query("regoin_short != 'California'").head()

,name,grape,region,variety,rating,notes,variety_short,regoin_short
7,12 Linajes Crianza 2014,NaN,"Ribera del Duero, Spain",Red Wine,92.0,Red with violet hues. The aromas are very inte...,R,Spain
8,12 Linajes Reserva 2012,NaN,"Ribera del Duero, Spain",Red Wine,94.0,"On the nose, a complex predominance of mineral...",R,Spain
9,14 Hands Cabernet Sauvignon 2010,NaN,"Columbia Valley, Washington",Red Wine,87.0,Concentrated aromas of dark stone fruits and t...,R,Washington
10,14 Hands Cabernet Sauvignon 2011,NaN,"Columbia Valley, Washington",Red Wine,89.0,Concentrated aromas of dark stone fruits and t...,R,Washington
11,14 Hands Cabernet Sauvignon 2015,NaN,"Columbia Valley, Washington",Red Wine,89.0,"The 14 Hands Cabernet Sauvignon is a rich, jui...",R,Washington